name: NuNuGet CI
on:
  pull_request:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.editorconfig'
      - '.vscode/**'
      - '*.md'
  workflow_dispatch:
    inputs:
      force-release:
        type: boolean
        default: false
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.rid }})
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        rid: [any, win-x64, win-arm64, linux-x64, linux-arm64, osx-arm64]
        include:
          - rid: any
            os: ubuntu-22.04
            checkFormatting: true
            buildRootPackage: true
          - rid: win-x64
            os: windows-2025
          - rid: win-arm64
            os: windows-2025
          - rid: linux-x64
            os: ubuntu-26.04
          - rid: linux-arm64
            os: ubuntu-26.04-arm
          - rid: osx-arm64
            os: macos-15
    env:
      PUBLISH_PROFILE: SingleFileSelfContainedTrimmedAot
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: false
          fetch-depth: 0
          filter: blob:none

      - name: Machine Setup
        uses: ./.github/actions/machine-setup

      - name: Restore
        shell: pwsh
        run: |
          & dotnet restore

      - name: Check formatting
        if: ${{ matrix.checkFormatting }}
        shell: pwsh
        run: |
          & dotnet format --no-restore --verify-no-changes

      - name: Build, Test, Pack - Debug
        uses: ./.github/actions/build-test-pack
        with:
          configuration: Debug
          runtime: ${{ matrix.rid }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          publish-project: ./NuNuGet/NuNuGet.csproj
          log-path: __artifacts/

      - name: Build, Test, Pack - Release
        uses: ./.github/actions/build-test-pack
        with:
          configuration: Release
          runtime: ${{ matrix.rid }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          publish-project: ./NuNuGet/NuNuGet.csproj
          log-path: __artifacts/

      - name: Build 'Root' Package
        if: ${{ matrix.buildRootPackage }}
        shell: pwsh
        run: |
          & dotnet pack ./NuNuGet/NuNuGet.csproj `
                        --configuration Debug `
                        /p:PublishProfile=${{ env.PUBLISH_PROFILE }} `
                        /bl:__artifacts/msbuild.pack-root.Debug.binlog

          & dotnet pack ./NuNuGet/NuNuGet.csproj `
                        --configuration Release `
                        /p:PublishProfile=${{ env.PUBLISH_PROFILE }} `
                        /bl:__artifacts/msbuild.pack-root.Release.binlog

      - name: Upload 'package' artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: __artifacts_package_${{ matrix.rid }}
          path: |
            __artifacts/package

      - name: Upload 'msbuild_binlog' artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: __artifacts_msbuild_binlog_${{ matrix.rid }}
          path: |
            __artifacts/msbuild.*.binlog

  create-release:
    name: Create release and upload assets
    needs: build
    runs-on: ubuntu-slim
    permissions:
      actions: read
      contents: write
    if: ${{ inputs.force-release || (github.event_name == 'push' && contains(fromJSON('["refs/heads/main"]'), github.ref)) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: false
          fetch-depth: 0
          filter: blob:none

      - name: Machine Setup
        uses: ./.github/actions/machine-setup

      - name: Download package artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: __artifacts_package_*
          path: __artifacts/package
          merge-multiple: true

      - name: Get version
        id: get_version
        shell: pwsh
        run: |
          # Since this build is only on 'main', use the 'NuGetPackageVersion' variant of the 'nbgv' version.
          # This will not include the build-identifiers in the version, which we want for a public release.
          $Version = (& dotnet nbgv get-version --variable NuGetPackageVersion)
          if (-not $Version) { Write-Error 'Version not found'; exit 1 }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "version=$Version"

      - name: Create release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          $Version = $env:VERSION
          if (-not $Version) { Write-Error 'Version not found'; exit 1 }

          $RefName = if ('${{ github.ref }}' -match 'refs/heads/(.*)') { $Matches[1] }

          Write-Host "Logging into gh"
          Write-Output $env:GITHUB_TOKEN | gh auth login --with-token

          Write-Host "Creating draft release 'v$Version'"
          $Arguments = @(
            "v$Version"
            "--draft"
            if ($Version -match '-') {
              "--prerelease"
            }
            if ($RefName) {
              "--target", $RefName
            }
            "--title", "v$Version"
            "--notes", ""
            "--latest=false"
          )
          gh release create @Arguments

          $files = Get-ChildItem -Path '__artifacts/package/release/MSchofie.*.nupkg' -ErrorAction SilentlyContinue
          if (-not $files) { Write-Host "No .nupkg files found to upload"; exit 0 }
          foreach ($file in $files) {
            Write-Host "Uploading $($file.Name)"
            gh release upload "v$Version" $file.FullName --clobber
          }
